# Generated by Django 3.0.6 on 2020-06-01 15:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sightseeing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited', models.CharField(choices=[('want to visit', 'want to visit'), ('visited', 'visited')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('suggest', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='rating',
        ),
        migrations.DeleteModel(
            name='VisitedLocation',
        ),
        migrations.AddField(
            model_name='review',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightseeing.Location'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personallocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sightseeing.Location'),
        ),
        migrations.AddField(
            model_name='personallocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
