# Generated by Django 3.0.6 on 2020-06-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0003_auto_20200602_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personallocation',
            name='visited',
        ),
        migrations.AddField(
            model_name='personallocation',
            name='status',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
