# Generated by Django 3.0.6 on 2020-06-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0005_merge_20200603_1443'),
        ('sightseeing', '0005_merge_20200603_1441'),
    ]

    operations = [
    ]
