# Generated by Django 3.0.6 on 2020-06-04 19:48

from django.db import migrations, models
import sightseeing.models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to=sightseeing.models.profile_directory_path),
        ),
    ]
