# Generated by Django 3.0.6 on 2020-06-04 19:51

from django.db import migrations, models
import sightseeing.models


class Migration(migrations.Migration):

    dependencies = [
        ('sightseeing', '0010_auto_20200604_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=sightseeing.models.profile_directory_path),
        ),
    ]
